services:
  db-product:
    image: postgres:16-alpine
    container_name: mo-db-product
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: product_db
    ports:
      - '5432:5432'
    volumes:
      - product-data:/var/lib/postgresql/data

  db-cart:
    image: postgres:16-alpine
    container_name: mo-db-cart
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cart_db
    ports:
      - '5433:5432'
    volumes:
      - cart-data:/var/lib/postgresql/data

  db-order:
    image: postgres:16-alpine
    container_name: mo-db-order
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order_db
    ports:
      - '5434:5432'
    volumes:
      - order-data:/var/lib/postgresql/data

volumes:
  product-data:
  cart-data:
  order-data:
