name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      # Prisma database URLs for e2e tests
      DATABASE_URL_PRODUCT: postgresql://postgres:postgres@localhost:5432/product_db
      DATABASE_URL_CART: postgresql://postgres:postgres@localhost:5433/cart_db
      DATABASE_URL_ORDER: postgresql://postgres:postgres@localhost:5434/order_db
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/product_db

    services:
      postgres-product:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: product_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      postgres-cart:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: cart_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5433:5432

      postgres-order:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: order_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5434:5432

    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - run: npm i
      - run: npx playwright install --with-deps
      - run: npm run db:generate:product && npm run db:generate:cart && npm run db:generate:order
      - run: npx nx format:check --base="remotes/origin/main"
      - run: npx nx run-many -t lint test typecheck build e2e
